project:
  type: website
  output-dir: _output

website:
  title: "Laurian Kaijage"
  description: "Marine Scientist | Ecological Data Manager | Portfolio & CV"
  site-url: "https://kaijage-laurian-data.netlify.app/"  # your actual domain
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com
      - icon: linkedin
        href: https://linkedin.com

listing:
  sort-ui: false
  filter-ui: false

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: false
    code-overflow: wrap

include-in-header:
  - text: '<meta name="google-site-verification" content="rAksDH-3nQI9AkpomZ0TorPzHNNAtou6UgFlTgN1nlo" />'

